# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-15 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170915_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='userImg',
            new_name='avatar',
        ),
    ]
