# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-15 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170916_0210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='avatar',
            new_name='userImg',
        ),
    ]
