# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-16 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170916_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_img_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
