# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-18 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_user_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'kullaıcı profili', 'verbose_name_plural': 'kullanıcı profilleri'},
        ),
    ]
