# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-22 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170918_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='control',
            field=models.BooleanField(default=False),
        ),
    ]
